image: gradle:7.3

stages:
  - build
  - test
  - coverage
  - checkstyle
  - jar

attempt-build:
  stage: build
  script: gradle assemble

unit-tests:
  stage: test
  script: gradle test -i
  artifacts:
    paths:
      - $CI_PROJECT_DIR/domain/build/reports/*

test-coverage:
  stage: coverage
  script: gradle jacocoTestCoverageVerification
  artifacts:
    when: on_failure
    paths:
      - $CI_PROJECT_DIR/domain/build/reports/*

checkstyle:
  stage: checkstyle
  script:
    - gradle checkstyleMain
    - gradle checkstyleTest
  artifacts:
    when: on_failure
    paths:
      - $CI_PROJECT_DIR/domain/build/reports/*

get_jar:
  stage: jar
  script: gradle distZip
  artifacts:
    when: always
    name: "commit: $CI_COMMIT_SHORT_SHA pipeline: $CI_PIPELINE_ID branch: $CI_COMMIT_BRANCH"
    paths:
      - $CI_PROJECT_DIR/domain/build/distributions/*
