image: gradle:7.3

stages:
  - build
  - test
  - coverage
  - checkstyle

attempt-build:
  stage: build
  script: gradle build

unit-tests:
  stage: test
  script: gradle test -i
  artifacts:
    paths: $CI_PROJECT_DIR/domain/build/reports/*

test-coverage:
  stage: coverage
  script: gradle jacocoTestCoverageVerification
  artifacts:
    paths: $CI_PROJECT_DIR/domain/build/reports/*

checkstyle:
  stage: checkstyle
  script:
    - gradle checkstyleMain
    - gradle checkstyleTest
  artifacts:
    paths: $CI_PROJECT_DIR/domain/build/reports/*
