image: gradle:7.3

apply plugin: 'jacoco'

stages:
  - build
  - test
  - coverage

attempt-build:
  stage: build
  script: gradle build

test:
  stage: test
  script: gradle test -i

test-coverage:
  stage: coverage
  script: gradle jacoco
