image: gradle:7.3

stages:
  - build
  - sample-stage
  - test

sample-job:
  stage: sample-stage
  script:
    - echo "Hello world"

attempt-build:
  stage: build
  script: gradle build

test:
  stage: test
  script: gradle test -i
