image: gradle:7.3

stages:
  - build
  - test
  - coverage

attempt-build:
  stage: build
  script: gradle build

test:
  stage: test
  script: gradle test -i
  artifacts:
    paths:
      - $CI_PROJECT_DIR/domain/build/reports/*

test-coverage:
  stage: coverage
  script: gradle jacocoTestReport
  artifacts:
    paths:
      - $CI_PROJECT_DIR/domain/build/reports/*
